### ISSUE TITLE
NLTK and setuptools issue?

### ISSUE THREAD

**Issue by nvjq** [Annotald/annotald#86]
I'm trying to install `annotald` in Ubuntu 16.04 LTS. `sudo pip install annotald` returns the following error:

```
Collecting annotald
Using cached annotald-1.3.7-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): argparse in /usr/lib/python2.7 (from annotald)
Requirement already satisfied (use --upgrade to upgrade): cherrypy in /usr/local/lib/python2.7/dist-packages (from annotald)
Collecting nltk==2.0.4 (from annotald)
  Using cached nltk-2.0.4.zip
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.21.tar.gz
    Extracting in /tmp/tmpOlg03f
    Now working in /tmp/tmpOlg03f/distribute-0.6.21
    Building a Distribute egg in /tmp/pip-build-00z8yU/nltk
    /tmp/pip-build-00z8yU/nltk/distribute-0.6.21-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-00z8yU/nltk/setup.py", line 32, in <module>
        del sdist.finders[:]
    AttributeError: 'module' object has no attribute 'finders'
    ---------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-00z8yU/nltk/
```

Is this some kind of issue with NLTK and setuptools? cf. https://github.com/Annotald/annotald/issues/77
Else, please could you tell me what I'm doing wrong? Thank you very much for your time.

**Comment by aecay** [comment]
I believe the problem can be fixed with the following command:

    pip install --no-cache-dir annotald

Does that allow installation to succeed?

**Comment by nvjq** [comment]
Thanks for the suggestion. Unfortunately the same error is returned with that command.

**Comment by aecay** [comment]
OK, thanks for checking.  I've created version 1.3.8 just now, which should not have this error.

**Comment by nvjq** [comment]
It installs fine now. Thank you so much for your help!
